### ISSUE TITLE
Test 'polydist/term-eval' under win64 in msvc12 failed

### ISSUE THREAD

**Issue by xtracko** [crocs-muni/EACirc#104]
This test fails only in Debug mode on win64 platform using msvc12 compiler. In release or on win32 platform it passes.

[Running: polydist/term-eval]
C:\Users\xtracko\Devel\EACirc\eacirc\self_tests\Tests.cpp(255): pOutput[0] == 0x2 failed for: ♠ == 2
C:\Users\xtracko\Devel\EACirc\eacirc\self_tests\Tests.cpp(255): pOutput[1] == 0x0 failed for: └ == 0
[Finished: 'polydist/term-eval' 1 test case failed (2 of 9 assertions failed)]

**Comment by mathius** [comment]
In Visual Studio 2013 (toolset 120), Debug mode all tests pass ok.

**Comment by mathius** [comment]
Assigned to Karel, since he knows the poly code best.
Can wait until keymaker paper is finished.

**Comment by Bender250** [comment]
Notes from debugging:
Polynomials are stored in little endian. So poly[0] is for last bit of the output.

PolynomialInterpreter, line 39:
                ret &= TERM_ITEM_EVAL_GENOME(cTermEx, inputs+i*sizeof(POLY_GENOME_ITEM_TYPE));
Is badly evaluated for the falling test. For 3. polynomial, the first term is evaluated as false and should be true.

So it looks, that the bug is from PolyCommonFunctions.h, line 85:
// Compilation for 64 bit platform.
#define TERM_ITEM_EVAL_GENOME(trm, input) TERM_ITEM_EVAL_8(trm, input).

I suppose, that 32 bits versions runs OK, because for evaluation of term, term_item_eval is used.

**Comment by Bender250** [comment]
Solved by #b69f5f9. Both before the bugfix and after have bit-to-bit same output.

Problem is only 30% less performance.
