### ISSUE TITLE
Oneclick doesn't shows error message for too long WU name

### ISSUE THREAD

**Issue by Bender250** [crocs-muni/EACirc#141]
In time of uploading WU's, Oneclick doesn't show error message from BOINC management "Message: WU name is too long"
* WU name is below 63 character (problem showed on WU shorter than 50 characters too), but BOINC management refuses it.
* To reproduce problem, create job with for example 15 character long WU_IDENTIFIER, than continue to upload WU's. Everything runs OK, but if you create job using BOINC management, you will receave error page (http://is.muni.cz/de/408351/BOINC_management_-_Work_-_Create.html).

**Comment by LuboO** [comment]
Longest possible name I managed to create is 45 characters. I will fix check in Oneclick application (so longer name won't be generated, now this check is broken).

With current state of php frontend, it is impossible for Perl script to detect this error. Error occurs after clicking "Create work" and script doesn't wait for final page with success message/errors (because it takes too long).

Possible solution is to modify php frontend, so that the error will occur right after clicking "Next step". This error can be then checked by Perl script.

**Comment by mathius** [comment]
For now, add a check to Oneclick. PHP frontend will be deprecated in some time, new BOINC instance is on its way.

**Comment by LuboO** [comment]
Check added in f5812cb91225b6b02114ee3baa626962bb252531
