### ISSUE TITLE
JVMSim - no comparison operators, 1000TV/300k gen

### ISSUE THREAD

**Issue by petrs** [crocs-muni/EACirc#163]

**Comment by Bender250** [comment]
Hi, will yours computations finish with current experiments?

I would like to run few experiments, they will take about 1 day, with CUDA binary... Please, tell me when I can run them.

**Comment by mhajas** [comment]
Hi, well in this time, there are just 1000TV/30k tests running, after them I need to run 1000TV/300k. But if you are in hurry, you can run tests before I run 1000TV/300. I will notice you when 30k tests will be finished.

**Comment by Bender250** [comment]
I'm not in hurry, in better case (with submitted paper), I'll need them in until 11.11., on worse case, I'll have no deadline.

How long do you expect to run 1000TV/300k? 2 weeks is completely OK.

**Comment by mhajas** [comment]
I think 2 weeks are 100% enough.

**Comment by Bender250** [comment]
May I change now the binary on Boinc to run (maximally) 2 day experiment?

**Comment by mitko501** [comment]
Yes, you can.

**Comment by Bender250** [comment]
My computations are done, you can continue :).

**Comment by mitko501** [comment]
I read in another issue, you want to run another computation. I figured out I have a lot of work in front of me so you can run it now if you want.

**Comment by Bender250** [comment]
I expect, that validation experiments for polynomials can be done until end of weekend. Watch issue https://github.com/crocs-muni/EACirc/issues/157.

**Comment by Bender250** [comment]
Please, 3 more days - Martin and Syso want another one random-random experiment, this time with 10 000 runs...

**Comment by Bender250** [comment]
I apologize for the overtime.

Now, Boinc is only yours. I and Martin are running other experiments on metacentrum, because Boinc is very unstable and also we have more computations, than can our laboratory take.

When you ran yours experiments, watch, if Centaur is working - you can check it by loading boinc administrations page - if it loads, then everything works. If it is offline, and also you cannot connect by ssh on centaur (from FI network, or VPN, or over aisa...), then write others, so we can restart Centaur.

If you want to use metacentrum too, I or Martin can show you how to do that.
